name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci-linux:
    name: CI Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install site
  ci-windows:
    name: CI Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install vcexpress2010
      run: choco install vcexpress2010
    - run: cat C:\ProgramData\chocolatey\logs\chocolatey.log
    - run: echo ::add-path::C:\Windows\Microsoft.NET\Framework\v4.0.30319
    - run: echo ::add-path::C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE
    - run: echo ::add-path::C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN
    - run: echo ::set-env name=LIB::C:\Program Files\Microsoft Visual Studio 10.0\VC\LIB;%LIB%
    - run: echo ::set-env name=LIB::C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib;%LIB%
    - run: echo ::set-env name=LIB::C:\Program Files\Microsoft SDKs\Windows\v7.0A\Lib;%LIB%
    - run: echo ::set-env name=INCLUDE::C:\Program FilesMicrosoft Visual Studio 10.0\VC\include;%INCLUDE%
    - name: Start VCTools
      run: call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x64
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install site

