name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: |
        nuget restore src/main/native/windows/dll/fax4j_dll.sln
        nuget restore src/main/native/windows/exe/fax4j_exe.sln
    - name: Setup MSBuild.exe
      if: matrix.os == 'windows-latest'
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install site

